#!/usr/bin/env bash

if [ $# -gt 0 ]; then
    if [ "$1" == "composer" ]; then
        shift 1
        docker-compose exec sbo_php \
            composer "$@"
    elif [ "$1" == "console" ]; then
        shift 1
        docker-compose exec sbo_php \
            php ./bin/console "$@"
    elif [ "$1" == "test" ]; then
        shift 1
        docker-compose exec sbo_php \
            php ./bin/phpunit -c phpunit.xml "$@"
    elif [ "$1" == "phpstan" ]; then
        shift 1
        docker-compose exec sbo_php \
            php ./vendor/bin/phpstan analyse
    elif [ "$1" == "phpcs" ]; then
        shift 1
        docker-compose exec sbo_php \
                php ./vendor/bin/phpcs -p --cache
    elif [ "$1" == "check" ]; then
        echo -e "\e[32m> Run tests \e[0m\n";
        docker-compose exec sbo_php php ./bin/phpunit -c phpunit.xml --stop-on-failure && \
        echo -e "\n\e[32m> Run PHPStan \e[0m\n" && \
        docker-compose exec sbo_php php ./vendor/bin/phpstan analyse && \
        echo -e "\e[32m> Run PHP CS \e[0m\n" && \
        docker-compose exec sbo_php php ./vendor/bin/phpcs -p --cache
    else
        echo "./develop: Unknown command '$@'"
    fi
else
    echo "./develop: You must specify some command"
fi
