version: '3'
services:
  sbo_php:
    container_name: "sbo.php"
    build: ./docker/php/
    environment:
      PHP_EXTENSION_XDEBUG: ${PHP_EXTENSION_XDEBUG:-false}
      NUMPROCS: 1
    volumes:
      - .:/var/www/sbo/current
