version: '3'
services:
  sbo_nginx:
    container_name: "sbo.nginx"
    image: nginx:1.17.6
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/sbo/current
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
  sbo_php:
    container_name: "sbo.php"
    build: ./docker/php/
    environment:
      PHP_EXTENSION_XDEBUG: ${PHP_EXTENSION_XDEBUG:-false}
      NUMPROCS: 1
    volumes:
      - .:/var/www/sbo/current
  sbo_db:
    container_name: "sbo.db"
    image: bondas83/mysql-native-password
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    command: [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "sbo"
      MYSQL_USER: "sbo"
      MYSQL_PASSWORD: "sbo"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

volumes:
  mysql:
    driver: local
